# As per https://github.com/pypa/setuptools/blob/main/docs/userguide/quickstart.rst
[build-system]
requires = ["setuptools==60.10.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.codespell]
skip = '.git,.github,*.pdf,*.svg,pyproject.toml'
ignore-words-list = 'te,ines'
